### ISSUE TITLE
Does not work when available locale names are in upper case

### ISSUE THREAD

**Issue by lagartoflojo** [jcasimir/locale_setter#1]
It's common to have locale names with upper case letters. For example, in Rails you might have an `en-US.yml` file. LocaleSetter downcases the requested locales and assumes that available locales are also in lower case. I've fixed this by generating a hash as a lookup table where the key is the locale name in lower case, and the value is the original locale name. I don't like it very much, because it generates the loopup table every time, but it works.

Here's the commit, test included:
https://github.com/familink/locale_setter/commit/23785d25b6ed2013eec74b8327a70761bb254088

**Comment by steveklabnik** [comment]
Locales are case insensitive, downcasing them all is the Right Thing To Do.

**Comment by lagartoflojo** [comment]
Ok, but as the gem works right now, when a user requests the locale "es-CL", and I have an "es-CL.yml" file in my app, it does not pick it up, and instead falls back to default_locale.

**Comment by steveklabnik** [comment]
I've pulled your fix in, that's totally correct. Thanks!
